/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 background.gltf 
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'
import * as THREE from 'three'

export default function Model(props: any) {
  const { nodes, materials } = useGLTF('/assets/background/background.gltf')
  return (
    <group {...props} dispose={null} scale={20}>
      <mesh geometry={(nodes.Object001 as THREE.Mesh).geometry} material={materials.Material__25__background_JPG_002} />
    </group>
  )
}

useGLTF.preload('/assets/background/background.gltf')
