/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 background.gltf 
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export default function Model(props: any) {
  const background = useRef<THREE.Group | null>()
  const { nodes, materials } = useGLTF('/assets/background/background.gltf')

  useFrame(({ clock }) => {
    if (background.current) {
      background.current.rotation.y = clock.getElapsedTime() / 50;
    }
  })

  return (
    <group ref={background} {...props} dispose={null} scale={20}>
      <mesh geometry={(nodes.Object001 as THREE.Mesh).geometry} material={materials.Material__25__background_JPG_002} />
    </group>
  )
}

useGLTF.preload('/assets/background/background.gltf')
